#!/bin/bash
git add . # tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name TheGamerman50
git config --global user.email thegamerman50@gmail.com
git commit -m "Class_04"
git push origin main
